services:
  teamcity:
    image: jetbrains/teamcity-server:2024.07
    restart: always
    ports:
      - "8111:8111"
    volumes:
      - /srv/teamcity/data:/data/teamcity_server/datadir
      - /srv/teamcity/logs:/opt/teamcity/logs
  agent:
    image: jetbrains/teamcity-agent:2024.07-linux-sudo
    restart: always
    environment:
      - SERVER_URL=http://teamcity:8111
      - DOCKER_IN_DOCKER=start
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/teamcity/agent-config:/data/teamcity_agent/conf
    depends_on: [ teamcity ]
    privileged: true
    user: root
