image:
  repository: 365074502389.dkr.ecr.us-east-1.amazonaws.com/tunefy-frontend-dev
  tag: "#{Octopus.Release.Number}"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ecr-creds

replicaCount: 2

service:
  type: NodePort
  port: 80
  targetPort: 80

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    alb.ingress.kubernetes.io/healthcheck-path: /
  hosts:
    - host: ""  # Sin restricción de host para acceso directo via ALB DNS
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 300m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 10
  periodSeconds: 5
