apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mon-grafana-alb-dns
  namespace: monitoring
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:365074502389:certificate/c441fd40-e83a-42f5-ad58-37652d295ac5
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS13-1-2-2021-06
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/group.name: grafana-group  # Share the same ALB with mon-grafana ingress
    alb.ingress.kubernetes.io/healthcheck-path: /api/health
spec:
  ingressClassName: alb
  rules:
  - http:  # No host specified - matches any hostname (including ALB DNS)
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mon-grafana
            port:
              number: 80
