[bastion]
bastion1 ansible_host=3.85.38.87 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/tunefy-dev-key.pem

[cp]
cp1 ansible_host=10.20.91.106 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/tunefy-dev-key.pem

[workers]
wk1 ansible_host=10.20.57.86 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/tunefy-dev-key.pem
wk2 ansible_host=10.20.69.221 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/tunefy-dev-key.pem

[teamcity]
tc1 ansible_host=10.20.95.119 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/tunefy-dev-key.pem

[octopus]
oc1 ansible_host=10.20.63.199 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/tunefy-dev-key.pem

# Grupo para aplicar el ProxyCommand solo a privados
[privados:children]
cp
workers
teamcity
octopus

[k8s:children]
cp
workers

[ci:children]
teamcity

[cd:children]
octopus
