[bastion]
bastion ansible_host=54.83.124.222 ansible_user=ubuntu

[cp]
cp1 ansible_host=10.20.85.119 ansible_user=ubuntu

[workers]
wk1 ansible_host=10.20.59.15 ansible_user=ubuntu

[teamcity]
tc1 ansible_host=10.20.52.176 ansible_user=ubuntu

[octopus]
oc1 ansible_host=10.20.58.174 ansible_user=ubuntu

[k8s:children]
cp
workers

[ci:children]
teamcity

[cd:children]
octopus

# Proxy/IP del bastion para saltar a privadas
[all:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q ubuntu@<BASTION_PUBLIC_IP>"'
