---
# Playbook temporal para instalar solo kubernetes
- name: Install kubernetes components
  hosts: k8s
  become: yes
  roles:
    - kubernetes

- name: Initialize control plane (kubeadm init + Calico)
  hosts: cp
  become: yes
  roles:
    - control-plane

- name: Join workers
  hosts: workers
  become: yes
  roles:
    - worker