#!/bin/bash
set -euo pipefail

# ============================================
# Deploy Tunefy Production Infrastructure
# ============================================

echo "========================================"
echo "🚀 Tunefy Production Infrastructure"
echo "========================================"
echo ""

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check prerequisites
echo "📋 Checking prerequisites..."

if ! command -v terraform &> /dev/null; then
    echo -e "${RED}❌ Terraform not found. Please install Terraform.${NC}"
    exit 1
fi

if ! command -v aws &> /dev/null; then
    echo -e "${RED}❌ AWS CLI not found. Please install AWS CLI.${NC}"
    exit 1
fi

# Check AWS credentials
if ! aws sts get-caller-identity &> /dev/null; then
    echo -e "${RED}❌ AWS credentials not configured. Run: aws configure${NC}"
    exit 1
fi

echo -e "${GREEN}✅ All prerequisites met${NC}"
echo ""

# Confirm
read -p "This will deploy infrastructure to AWS. Continue? (yes/no): " CONFIRM
if [ "$CONFIRM" != "yes" ]; then
    echo "Deployment cancelled."
    exit 0
fi

# PHASE 1: Network
echo ""
echo "========================================"
echo "📡 PHASE 1: Deploying Network (VPC)"
echo "========================================"
cd infra/terraform/network

if [ ! -f "terraform.tfvars" ]; then
    echo -e "${YELLOW}⚠️  terraform.tfvars not found. Copying from example...${NC}"
    cp terraform-prod.tfvars terraform.tfvars
    echo -e "${YELLOW}⚠️  Please edit terraform.tfvars and re-run this script${NC}"
    exit 1
fi

terraform init
terraform plan -out=network.tfplan
read -p "Review network plan. Apply? (yes/no): " APPLY
if [ "$APPLY" == "yes" ]; then
    terraform apply network.tfplan
    echo -e "${GREEN}✅ Network deployed${NC}"
else
    echo "Network deployment skipped."
    exit 0
fi

# Save outputs
VPC_ID=$(terraform output -raw vpc_id)
PUBLIC_SUBNETS=$(terraform output -json public_subnet_ids | jq -r '.[]' | paste -sd ',' -)
PRIVATE_SUBNETS=$(terraform output -json private_subnet_ids | jq -r '.[]' | paste -sd ',' -)

echo ""
echo "Network Outputs:"
echo "  VPC ID: $VPC_ID"
echo "  Public Subnets: $PUBLIC_SUBNETS"
echo "  Private Subnets: $PRIVATE_SUBNETS"
echo ""

# PHASE 2: Platform
echo "========================================"
echo "🏗️  PHASE 2: Deploying Platform (ECR, IAM, S3)"
echo "========================================"
cd ../platform

if [ ! -f "terraform.tfvars" ]; then
    echo -e "${YELLOW}⚠️  terraform.tfvars not found. Copying from example...${NC}"
    cp terraform-prod.tfvars terraform.tfvars
    echo -e "${YELLOW}⚠️  Please edit terraform.tfvars (set your domain) and re-run this script${NC}"
    exit 1
fi

terraform init
terraform plan -out=platform.tfplan
read -p "Review platform plan. Apply? (yes/no): " APPLY
if [ "$APPLY" == "yes" ]; then
    terraform apply platform.tfplan
    echo -e "${GREEN}✅ Platform deployed${NC}"
else
    echo "Platform deployment skipped."
    exit 0
fi

# Save outputs
INSTANCE_PROFILE=$(terraform output -raw nodes_instance_profile_name)
S3_BUCKET=$(terraform output -raw s3_postgresql_backups_bucket)

echo ""
echo "Platform Outputs:"
echo "  Instance Profile: $INSTANCE_PROFILE"
echo "  S3 Backup Bucket: $S3_BUCKET"
echo ""

# PHASE 3: Compute
echo "========================================"
echo "☸️  PHASE 3: Deploying Compute (K8s Cluster)"
echo "========================================"
cd ../compute-prod

# Create terraform.tfvars if not exists
if [ ! -f "terraform.tfvars" ]; then
    echo -e "${YELLOW}📝 Creating terraform.tfvars with outputs from previous modules...${NC}"
    
    # Get your public IP
    PUBLIC_IP=$(curl -s ifconfig.me)
    
    cat > terraform.tfvars <<EOF
# Auto-generated by deploy-prod-infrastructure.sh
project = "tunefy"
region  = "us-east-1"
env     = "prod"

# From network module
vpc_id = "$VPC_ID"
public_subnet_ids  = [$(echo $PUBLIC_SUBNETS | sed 's/,/", "/g' | sed 's/^/"/' | sed 's/$/"/')]
private_subnet_ids = [$(echo $PRIVATE_SUBNETS | sed 's/,/", "/g' | sed 's/^/"/' | sed 's/$/"/')]

# From platform module
nodes_instance_profile_name = "$INSTANCE_PROFILE"

# SSH config
key_name = "tunefy-prod-key"
allowed_ssh_cidr = "$PUBLIC_IP/32"

# Kubernetes
cluster_name = "tunefy-prod"
cp_instance_type      = "t3.small"
wk_instance_type      = "t3.micro"
bastion_instance_type = "t3.micro"

tags = {
  Owner       = "DevOps"
  Environment = "Production"
  ManagedBy   = "Terraform"
}
EOF
    
    echo -e "${GREEN}✅ terraform.tfvars created${NC}"
    echo -e "${YELLOW}⚠️  Please review terraform.tfvars (especially SSH key name)${NC}"
    read -p "Continue with these values? (yes/no): " CONTINUE
    if [ "$CONTINUE" != "yes" ]; then
        exit 0
    fi
fi

terraform init
terraform plan -out=compute.tfplan

echo ""
echo -e "${YELLOW}⚠️  This will create EC2 instances. Review the plan carefully!${NC}"
read -p "Apply compute plan? (yes/no): " APPLY
if [ "$APPLY" == "yes" ]; then
    terraform apply compute.tfplan
    echo -e "${GREEN}✅ Compute deployed${NC}"
else
    echo "Compute deployment skipped."
    exit 0
fi

# Save outputs
BASTION_IP=$(terraform output -raw bastion_public_ip)
CP_IP=$(terraform output -json cp_private_ips | jq -r '.[0]')
NLB_DNS=$(terraform output -raw nlb_dns_name)

echo ""
echo "========================================"
echo "🎉 Infrastructure Deployment Complete!"
echo "========================================"
echo ""
echo "📝 Important Outputs:"
echo "  Bastion IP:    $BASTION_IP"
echo "  Control Plane: $CP_IP"
echo "  NLB DNS:       $NLB_DNS"
echo ""
echo "🔐 SSH Access:"
echo "  ssh -i tunefy-prod-key.pem ubuntu@$BASTION_IP"
echo "  ssh ubuntu@$CP_IP  # From bastion"
echo ""
echo "📖 Next Steps:"
echo "  1. Wait ~5 minutes for Kubernetes cluster to initialize"
echo "  2. Follow DEPLOYMENT-GUIDE-PROD.md from FASE 2"
echo "  3. Verify cluster: ssh to bastion, then CP, run 'kubectl get nodes'"
echo ""

# Save outputs to file
cat > deployment-outputs.txt <<EOF
Tunefy Production Deployment Outputs
Generated: $(date)

VPC ID: $VPC_ID
Public Subnets: $PUBLIC_SUBNETS
Private Subnets: $PRIVATE_SUBNETS

Instance Profile: $INSTANCE_PROFILE
S3 Backup Bucket: $S3_BUCKET

Bastion IP: $BASTION_IP
Control Plane IP: $CP_IP
NLB DNS: $NLB_DNS

SSH Commands:
  Bastion: ssh -i tunefy-prod-key.pem ubuntu@$BASTION_IP
  CP from Bastion: ssh ubuntu@$CP_IP
EOF

echo -e "${GREEN}📄 Outputs saved to: deployment-outputs.txt${NC}"
echo ""



